version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t kraaarpit/multi-client ./client
          docker build -t kraaarpit/multi-nginx ./nginx
          docker build -t kraaarpit/multi-server ./server
          docker build -t kraaarpit/multi-worker ./worker
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push kraaarpit/multi-client
          docker push kraaarpit/multi-nginx
          docker push kraaarpit/multi-server
          docker push kraaarpit/multi-worker



workflows:
  build_and_test:
    jobs:
      - build